In [2]:
# numpy: python.org-->pypi.org --> 200000+ Lakh 



In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np
a=np.array([[3,2,1],[4,3,2],[1,2,1]])

In [7]:
print(a)
a.shape

[[3 2 1]
 [4 3 2]
 [1 2 1]]


(3, 3)

In [8]:
b=np.array([1,2,1])
print(b)
print(b.shape)

[1 2 1]
(3,)


In [9]:
a*b

array([[3, 4, 1],
       [4, 6, 2],
       [1, 4, 1]])

In [10]:
# scaler --> 0 Dimensional array

In [24]:
a=np.array(1)   # 0 Dimensional array
print(a)

1


In [18]:
b=np.array([1,2,3,4,5])
print(b)

[1 2 3 4 5]


In [21]:
c=np.array([[1,2,3],[3,4,1]])  # 2 Dimension array
print(c)

[[1 2 3]
 [3 4 1]]


In [23]:
d=np.array([[[1,3,4],[1,2,3]]])
print(d)

[[[1 3 4]
  [1 2 3]]]


In [26]:
255*254*253

16386810

In [27]:
1440*1920*3

8294400

In [1]:
import numpy as np

In [7]:
a=np.array(10)
print(a)
print(type(a))
print(a.ndim)
print(a.shape)

10
<class 'numpy.ndarray'>
0
()


In [13]:
b=np.array([1,2,3,4])
print(b)
print(b.ndim)
print(b.shape)

[1 2 3 4]
1
(4,)


In [14]:
c=np.array([[1,2,3,4]])
print(c)
print(c.ndim)
print(c.shape)

[[1 2 3 4]]
2
(1, 4)


In [15]:
d=np.array([[[1,2,3,4]]])
print(d)
print(d.ndim)
print(d.shape)

[[[1 2 3 4]]]
3
(1, 1, 4)


In [16]:
d=np.array([[[[1,2,3,4]]]])
print(d)    #[[[[1 2 3 4]]]]
print(d.ndim)   #4
print(d.shape)  #(1, 1, 1, 4)

[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)


In [4]:
a=[[1,3],[2,3,4],[3,5,6]]
print(a)
print(type(a))

[[1, 3], [2, 3, 4], [3, 5, 6]]
<class 'list'>


In [10]:
import numpy as np
a=np.array([[1,2,3],[2,3,0]])
print(a)
print(type(a))

[[1 2 3]
 [2 3 0]]
<class 'numpy.ndarray'>


In [14]:
np.zeros((2,2,2,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [1]:
# Date : 3/5/2023

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])

In [4]:
print(a)

[1 2 3 4]


In [5]:
type(a)

numpy.ndarray

In [14]:
np.arange(10)  # this belong to numpy return an iterable and it value inside an array   

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
range(10)  # this belongs to python only return iterable 

range(0, 10)

In [15]:
np.arange(0,10)  # start value_will be 0 bydefault,end value(exclusive), step(bydefault 1)  

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,10,1) # start value, end value, step

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
np.arange(2,10,3)

array([2, 5, 8])

In [21]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [23]:
np.array([i for i in range(10)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a=[i for i in range(100)]
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [27]:
b=np.array(a)

In [28]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [29]:
import sys

In [30]:
sys.getsizeof(a)  # list use higher value as compare to array with same number of elments, hence it faster

920

In [32]:
sys.getsizeof(b)  # array aquire less space as compare to list

512

In [33]:
len(a)

100

In [34]:
len(b)

100

In [35]:
# precedence
# array: a collection which contain similar datatype called array.it never allows hetrogenous(dis similar datatype) datatype

In [38]:
np.array([1,2.343,"krishna"])

array(['1', '2.343', 'krishna'], dtype='<U32')

In [39]:
np.array([1,2.343])

array([1.   , 2.343])

In [40]:
np.array([1,1,2,3,4])

array([1, 1, 2, 3, 4])

In [44]:
np.array([1,2.343,"krishna"],dtype=np.int128)

AttributeError: module 'numpy' has no attribute 'int128'

In [45]:
np.array([1,2.343,"krishna"],dtype=np.int64)

ValueError: invalid literal for int() with base 10: 'krishna'

In [52]:
a=np.array([1,2.343,"10"],dtype=np.int8)
print(a)
sys.getsizeof(a)

[ 1  2 10]


115

In [53]:
b=np.array([1,2.343,"10"],dtype=np.int64)
print(b)
sys.getsizeof(b)

[ 1  2 10]


136

In [56]:
c=np.array([1,2.343,"10"],dtype=np.float64)

In [57]:
print(c)

[ 1.     2.343 10.   ]


In [62]:
d=np.array([1,2.343,"10.0"],dtype=np.float32)
print(d)

[ 1.     2.343 10.   ]


In [63]:
e=np.array(d,dtype=np.int8)

In [64]:
print(e)

[ 1  2 10]


In [65]:
e=np.array(np.array([1,2.343,"10.0"],dtype=np.float32),dtype=np.int8)

In [66]:
print(e)

[ 1  2 10]


In [67]:
print(e)

[ 1  2 10]


In [68]:
np.array(e,dtype=np.str_)

array(['1', '2', '10'], dtype='<U4')

In [71]:
np.ones((3,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [72]:
np.ones((2,3,10))

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [74]:
np.ones((3,2,3,1))


array([[[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]]])

In [77]:
np.zeros((3,2,10))

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [79]:
np.array(np.full((10,),20),dtype=np.float32)

array([20., 20., 20., 20., 20., 20., 20., 20., 20., 20.], dtype=float32)

In [80]:
np.zeros((10,))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [81]:
np.ones((10,))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [82]:
np.full((10,),2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [83]:
np.full((10,),3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [85]:
a=np.full((10,),4)

In [87]:
np.array(np.full((10,),4),dtype=np.str_)

array(['4', '4', '4', '4', '4', '4', '4', '4', '4', '4'], dtype='<U11')

In [92]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [89]:
10-1

9

In [95]:
np.linspace(1,100,5)  #start, end,size  (start and end both are inclusive)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [143]:
np.random.randint(1,7,(3,2,10))  # start,end(exclusive),matrix size(tuple)

array([[[3, 5, 6, 6, 3, 6, 3, 4, 2, 3],
        [3, 1, 1, 4, 5, 4, 3, 2, 6, 4]],

       [[4, 1, 4, 4, 6, 4, 4, 5, 2, 1],
        [3, 1, 5, 5, 1, 6, 3, 3, 4, 5]],

       [[1, 2, 5, 6, 6, 3, 1, 2, 1, 5],
        [5, 6, 4, 5, 1, 4, 4, 3, 2, 5]]])

In [146]:
np.random.randint(1,7) 

2

In [1]:
# Date:-4/5/2023

In [2]:
import numpy as np

In [6]:
a=np.random.randint(1,10,10)

In [7]:
print(a)

[8 8 5 3 3 6 8 2 4 1]


In [9]:
np.random.randint(1,10,(10,))

array([4, 6, 1, 9, 1, 1, 5, 9, 2, 6])

In [11]:
np.random.randint(1,10,(10,2))

array([[5, 9],
       [1, 4],
       [1, 4],
       [1, 1],
       [7, 5],
       [8, 4],
       [8, 8],
       [8, 3],
       [2, 2],
       [8, 4]])

In [15]:
a=np.random.randint(1,10,(10,2,3))
print(a)

[[[4 4 9]
  [9 3 2]]

 [[7 9 1]
  [4 8 9]]

 [[4 4 8]
  [4 2 9]]

 [[3 5 2]
  [9 5 7]]

 [[8 5 4]
  [4 9 5]]

 [[1 7 8]
  [4 6 7]]

 [[7 9 1]
  [2 7 9]]

 [[3 4 1]
  [3 4 9]]

 [[2 4 4]
  [6 7 6]]

 [[8 4 6]
  [3 8 1]]]


In [18]:
a=np.random.randint(1,10,(2,3))

In [19]:
a

array([[5, 1, 8],
       [2, 2, 2]])

In [24]:
a.flatten()    # bydefault numpy array 2d or nd dimensional array flatten in 1D using C programming array referance.

array([5, 1, 8, 2, 2, 2])

In [25]:
a.flatten(order="C")

array([5, 1, 8, 2, 2, 2])

In [27]:
a.flatten(order='F') # bydefault numpy array 2d or nd dimensional array flatten in 1D using Fortran programming array referance.

array([5, 2, 1, 2, 8, 2])

In [29]:
a=np.array([i for i in range(10)])

In [30]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
a.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
a.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [33]:
a.reshape(6,10)


ValueError: cannot reshape array of size 10 into shape (6,10)

In [34]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a.resize((2,3),refcheck=False)

In [38]:
print(a)

[[0 1 2]
 [3 4 5]]


In [40]:
a.resize((2,2),refcheck=False)

In [41]:
print(a)

[[0 1]
 [2 3]]


In [49]:
a=np.random.randint(1,10,(12))

In [50]:
print(a)

[4 7 3 3 3 3 7 2 9 4 2 5]


In [53]:
a.reshape(2,-1)

array([[4, 7, 3, 3, 3, 3],
       [7, 2, 9, 4, 2, 5]])

In [56]:
a.reshape(1,1,-1,2)

array([[[[4, 7],
         [3, 3],
         [3, 3],
         [7, 2],
         [9, 4],
         [2, 5]]]])

In [57]:
a.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [59]:
a=[1,2,3,4]
b=[3,4,5,6]

In [60]:
a+b

[1, 2, 3, 4, 3, 4, 5, 6]

In [66]:
c=np.array([1,2,3,4])
d=np.array([[[3,4,5,6],[1,2,3,4]]])
print(c+d)

[[[ 4  6  8 10]
  [ 2  4  6  8]]]


In [68]:
np.concatenate((a,b))

array([1, 2, 3, 4, 3, 4, 5, 6])

In [73]:
c*3

array([ 3,  6,  9, 12])

In [72]:
a*3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [74]:
c

array([1, 2, 3, 4])

In [77]:
c.resize(1,2,refcheck=False)

In [78]:
print(c)

[[1 2]]


In [79]:
[1,2,3,4]+[3,4,5,6]

[1, 2, 3, 4, 3, 4, 5, 6]

In [83]:
a=[1,2,3,4]
b=[3,4,5,6]
cont=[i+j for i,j in zip(a,b)]
# for i,j in zip(a,b):
#     print(i,j)
#     cont.append(i+j)
print(cont)


[4, 6, 8, 10]
